# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test
data:
  AUTH0_ISSUER: "https://dev-sivm85jjcaa1qkih.us.auth0.com"
  AUTH0_USERINFO_URL: "https://dev-sivm85jjcaa1qkih.us.auth0.com/userinfo"
  ELASTICSEARCH_PASSWORD: "DkIedPPSCb"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  POSTGRES_DB: "prototype1"
  POSTGRES_PASSWORD: "avizva9372"
  POSTGRES_URL: "postgres"
  POSTGRES_USER: "postgres"
  HOST_URL: "host.docker.internal"
  STRIPE_API_KEY: "pk_test_51OwORDP4LTe9UnOS716sBGg0ch4lXrlVVAjFprMbD64jYpscTovuqE1wP7rUFfqLry2nhsWSPUU2r8eaNaXUKS3d00Lfj3t8OZ"
